manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmk
      revision: main
    - name: jimpad_v1
      remote: zmk
      path: boards/shields/jimpad_v1  # Set the path to your board definition files
      revision: main
  self:
    path: zmk
