manifest:
  version: "0.7"

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      repo-path: zmk
      revision: main
      path: app

  self:
    path: app
